===================================
 The ``101-lazy_matrix_mul`` module
===================================

Testing ``lazy_matrix_mul`` function

>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

Testing cases:

>>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
array([[ 7, 10],
       [15, 22]])

>>> lazy_matrix_mul([[1, 2]], [[3, 4], [5, 6]])
array([[13, 16]])

>>> lazy_matrix_mul([[1, 2, 3], [3, 4, 6]], [[1, 2, 4], [3, 4, 7], [3, 4, 7]])
array([[16, 22, 39],
       [33, 46, 82]])

>>> lazy_matrix_mul([[-1, -4.5, 8], [-4, 45, 0]], [[-3, 6, 6.7], [3, -78, 89], [5, 2, 1]])
array([[   29.5,   361. ,  -399.2],
       [  147. , -3534. ,  3978.2]])

>>> lazy_matrix_mul("I am no a list", [[1, 2], [3, 4]])
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead

>>> lazy_matrix_mul( [[1, 2], [3, 4]], "I am no a list")
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead

>>> lazy_matrix_mul( ["I am no a list", [3, 4]], [[1, 2], [3, 4]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence

>>> lazy_matrix_mul([[1, 2], [3, 4]], ["I am no a list", 3.2])
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> lazy_matrix_mul([], [[1, 2], [3, 4]])
Traceback (most recent call last):
ValueError: shapes (0,) and (2,2) not aligned: 0 (dim 0) != 2 (dim 0)

>>> lazy_matrix_mul([[]], [[1, 2], [3, 4]])
Traceback (most recent call last):
ValueError: shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)

>>> lazy_matrix_mul([[1, 2], [3, 4]], [])
Traceback (most recent call last):
ValueError: shapes (2,2) and (0,) not aligned: 2 (dim 1) != 0 (dim 0)

>>> lazy_matrix_mul([[1, 2], [3, 4]], [[]])
Traceback (most recent call last):
ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

>>> lazy_matrix_mul([[1, "A"]], [[3, 4], [5, 6]])
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> lazy_matrix_mul([[1, 2]], [[3, "A"], [5, 6]])
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> lazy_matrix_mul([[1], [1, 2]], [[3, 4], [5, 6]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> lazy_matrix_mul([[1, 3], [1, 2]], [[3], [5, 6]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> lazy_matrix_mul([[1, 2, 3]], [[5, 6], [7, 8]])
Traceback (most recent call last):
ValueError: shapes (1,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

>>> lazy_matrix_mul([[1, 2], [3, 4]], [[1.5, 2.5, 3.5], [4.5, 6.5, 7.5]])
array([[10.5, 15.5, 18.5],
       [22.5, 33.5, 40.5]])

>>> ms = __import__("101-lazy_matrix_mul").__doc__
>>> len(ms) > 1
True

>>> fs = __import__("101-lazy_matrix_mul").__doc__
>>> len(fs) > 1
True

>>> lazy_matrix_mul([[1, 2], [3, 4]])
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

>>> lazy_matrix_mul()
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'
